spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: info
    sql: debug

# actuator 설정
# 기본적으로 localhost:8080/actuator 셋팅 됨
# 들어가서 해당 부분의 정보를 주소로 치면 상세 하게 볼 수 있음
management:
  endpoints:
    web:
      path-mapping:
        health: /health
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET, POST, PUT
